version: 2
jobs:
    build:
        docker:
            - image: circleci/node:14-browsers

        working_directory: ~/intercom-node

        steps:
            - checkout
            - run: export PATH="${PATH}:/home/circleci/.yarn/bin"
            - run: npm install --prefix=$HOME/.local --global corepack
            - run: yarn
            - run: yarn test

notify:
    webhooks:
        - url: https://muster.intercom.io/circle_webhooks
