version: 2
jobs:
    build:
        docker:
            - image: circleci/node:14-browsers
        working_directory: ~/intercom-node
        steps:
            - checkout
            - run: export PATH="${PATH}:/home/circleci/.yarn/bin"
            - run: npm install --prefix=$HOME/.local --global corepack
            - restore_cache:
                  key: dependency-cache-{{ checksum "yarn.lock" }}
            - run: yarn
            - save_cache:
                  key: dependency-cache-{{ checksum "yarn.lock" }}
                  paths:
                      - node_modules
            - run: yarn prepublish
    unit_test:
        docker:
            - image: circleci/node:14-browsers
        working_directory: ~/intercom-node
        steps:
            - checkout
            - restore_cache:
                  key: dependency-cache-{{ checksum "yarn.lock" }}
            - run: yarn test:unit
    integration_test:
        docker:
            - image: circleci/node:14-browsers
        working_directory: ~/intercom-node
        steps:
            - checkout
            - restore_cache:
                  key: dependency-cache-{{ checksum "yarn.lock" }}
            - run: export $API_TOKEN
            - run: yarn test:integration

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - unit_test:
                  requires:
                      - build
            - integration_test_approval:
                  requires:
                      - build
                  type: approval
            - integration_test:
                  requires:
                      - integration_test_approval

notify:
    webhooks:
        - url: https://muster.intercom.io/circle_webhooks
